<?php

/**
 * @file
 * Syncart: syncart.module.
 */

use Drupal\views\ViewExecutable;
use Drupal\syncart\Controller\SynCart;
use Drupal\syncart\Controller\ProductVariationAlter;

/**
 * Implements hook_views_pre_view().
 */
function syncart_views_pre_view(ViewExecutable $view, $display_id, array &$args) {

  if ($view->id() == 'commerce_cart_form' && ($display_id == 'block_1' || $display_id == 'block_2')) {
    $cartManager = new SynCart(FALSE);
    $cid = $cartManager->cart->id();
    if (!empty($cid)) {
      $args[0] = $cid;
    }

  }
}

/**
 * Implements hook_page_attachments().
 */
function syncart_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'syncart/syncart';
}

/**
 * Implements hook_view().
 */
function syncart_node_view(array &$build, $entity, $display, $view_mode) {
  ProductVariationAlter::init($build, $entity);
}

/**
 * Implements hook_theme().
 */
function syncart_theme() {
  return [
    'answer-card-add' => [
      'template' => 'answer-card-add',
      'variables' => ['data' => [], 'info' => []],
    ],

    'total-cart' => [
      'template' => 'total-cart',
      'variables' => ['data' => [], 'info' => []],
    ],
  ];
}
