<?php

/**
 * @file
 * Syncart: syncart.module.
 */

use Drupal\views\ViewExecutable;
use Drupal\syncart\Controller\SynCart;
use Drupal\Core\Url;
use Drupal\Core\Link;

/**
 * Implements hook_views_pre_view().
 */
function syncart_views_pre_view(ViewExecutable $view, $display_id, array &$args) {

  if ($view->id() == 'commerce_cart_form' && ($display_id == 'block_1' || $display_id == 'block_2')) {
    $cartManager = new SynCart(FALSE);
    $cid = $cartManager->cart->id();
    if (!empty($cid)) {
      $args[0] = $cid;
    }

  }
}

/**
 * Implements hook_page_attachments().
 */
function syncart_page_attachments(array &$page) {
  $page['#attached']['library'][] = 'syncart/syncart';
}

/**
 * Implements hook_view().
 */
function syncart_node_view(array &$build, $entity, $display, $view_mode) {
  $node_type = $entity->getType();
  if ($node_type == 'tovar') {
    $nid = $entity->id();

    $options = ['attributes' => ['class' => ['use-ajax', 'syncart-link']]];
    if (property_exists($entity, 'field_tovar_variation')) {
      $variations = $entity->field_tovar_variation->getValue();
      foreach ($variations as $key => $variation) {
        $pid = $variation['target_id'];
        $extra = [
          'nid' => $nid,
          'pid' => $pid,
        ];
        $url = Url::fromRoute('cartadd', $extra);
        $url->setOptions($options);
        $config = \Drupal::config('syncart.settings');
        if ($config->get('link')) {
          $build['syncart']['cart-' . $pid]['link'] = [
            '#markup' => Link::fromTextAndUrl('В корзину', $url)->toString(),
          ];
        }
        if ($config->get('form')) {
          $build['syncart']['cart-' . $pid]['form'] = [
            'form' => \Drupal::formBuilder()->getForm('Drupal\syncart\Form\AddToCart', $extra),
          ];
        }
      }
    }
  }
}

/**
 * Ajax().
 */
function _syncart_ajax() {
  return TRUE;
}

/**
 * Implements hook_theme().
 */
function syncart_theme() {
  return [
    'answer-card-add' => [
      'template' => 'answer-card-add',
      'variables' => ['data' => [], 'info' => []],
    ],

    'total-cart' => [
      'template' => 'total-cart',
      'variables' => ['data' => [], 'info' => []],
    ],
  ];
}
